---
- name: Install local ansible data path directory
  tags: maven
  sudo: no
  local_action: file
    state=directory
    mode=2777
    dest={{ local_ansible_data_path }}


- name: Download Maven
  tags: maven
  sudo: no
  local_action: get_url
    dest={{ local_ansible_data_path }}/{{ maven_redis_filename }}
    url={{ maven_mirror }}/{{ maven_redis_filename }}
    mode=0644
    sha256sum={{ maven_redis_sha256sum }}
